name: Build
on:
  push:
    branches:
      - '**'
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - run: ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: bin/nuget