name: Build
on:
  push:
    branches: ['**']
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Build & Test
        run: ./build.sh --target Default
      - name: Release & Publish
        if: github.ref == 'refs/heads/master'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./build.sh --target Release
      - name: Generate Documentation
        if: github.ref == 'refs/heads/master'
        run: ./build.sh --target GenerateDocs
      - name: Publish Documentation
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output